name: Swahilipot FM Website CI

on:
  pull_request:
    branches:
      - main
      - dev
      - Marhabaa
      - vincent

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install dependencies
        run: npm ci
      - name: Check formatting with Prettier
        run: npm run check-format
      - name: Build the app
        run: npm run build